
[general]
positions_file = "positions.txt"

server_port = 2001
logger_interval = 1.0

timeout_move = 600.0 # in seconds

[precision]
do_precision = false
maxsteps = 10
maxiter = 10
correctess = false # use with care!
doublepass = true

# individual disc settings take precedence, use global disc setting if none specified individually
[devices.general]
    timeout_connect = 10.0

    mc_port = 2000
    ids_port = 9090

    # global disc settings
    temp = 300
    flextol = 300
    flexdist = 5000
    df = 1.0
    mrss = [10,10,10]
    freq = [50,70] # [master,slave]

    r = 0.15

[devices.1] # individual disc settings
    mc  = "192.168.2.1"
    ids = "192.168.3.1"
    
    master = 1
    ess = [15e-6,15e-6,15e-6]
    alpha = 0.0

[devices.2]
    mc  = "192.168.2.2"
    ids = "192.168.3.2"
    
    master = 1
    ess = [15e-6,15e-6,15e-6]
    alpha = 0.0

[devices.3]
    mc  = "192.168.2.3"
    ids = "192.168.3.3"
    
    master = 1
    ess = [15e-6,15e-6,15e-6]
    alpha = 0.0