
[general]
positions_file = "positions.txt"

server_port = 2001                      # port for motor control server
logger_interval = 1.0                   # interval for updating IDS data to logger

timeout_move = 600.0 # seconds          # timeout for motors to reach their targets [NYI]
rezero = false                          # wether to rezero devices on boot. use with care

# if a setting not specified, falls back to the defaults given in blackmage
[precision]                             # precision correction settings
doprecision = false                     # do corrections after reaching target?
maxsteps = 10                           # max individual correction steps per iteration
maxiter = 10                            # max correction iteration
correctess = false                      # update estimated step size? use with great care!     
doublepass = true                       # do a second correction pass?

# individual disc settings take precedence
# use global disc setting if none specified individually
# if a setting is not specified, falls back to defaults given in blackmage
[devices.general]
    timeout_connect = 10.0 # seconds    # timeout for connecting to each motor and IDS device

    mc_port = 2000                      # motor control port
    ids_port = 9090                     # interferometer port

    # global disc settings
    temp = 300 # Kelvin                 # ambient motor temperature
    flextol = 300 # IDS units           # target tolerance for move commands in IDS units
    flexdist = 5000 # IDS units         # distance tolerance between moving motors in IDS units
    df = 1.0                            # drive factor (yeah idk either, just leave at 1 tbh)
    freq = [50,70] # [master,slave]     # 

    mrss = [10,10,10] # % of full step  # minimum allowed relative step size for corrections
                                        # if well known, set individually?

    r = 0.15 # meters                   # distance of interferometer mirrors from disc center
                                        # used for tilt calculations 

[devices.1] # individual disc settings
    mc  = "192.168.2.1"                 # ip address of motor control
    ids = "192.168.3.1"                 # ip address of interferometer
    
    master = 1                          # master axis (this could also be set globally if uniform)
    ess = [15e-6,15e-6,15e-6] # m       # estimated size of single motor step for corrections
    alpha = 0.0 # degrees               # angle of axis 1 wrt global reference plane
                                        # this depends on the rail frame construction
                                        # and will have to be measured and set individually
                                        # this is necessary for calculating disc tilts with
                                        # to a common reference

[devices.2]
    mc  = "192.168.2.2"
    ids = "192.168.3.2"
    
    master = 1
    ess = [15e-6,15e-6,15e-6]
    alpha = 0.0

[devices.3]
    mc  = "192.168.2.3"
    ids = "192.168.3.4"
    
    master = 1
    ess = [15e-6,15e-6,15e-6]
    alpha = 0.0